#pragma config(Motor,  port1,           M1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           R1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port3,           R2,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port4,           L1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port5,           L2,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          M2,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (true)
{
	//forwardbackward drive
	motor[R1]=vexRT[Ch2];
	motor[R2]=vexRT[Ch2];
	motor[L2]=vexRT[Ch3];
	motor[L2]=vexRT[Ch3];

	//leftright drive
	motor[M1]=vexRT[Ch1];
	motor[M2]=vexRT[Ch1];

	//turn
	motor[R1]=vexRT[Ch4];
	motor[R2]=vexRT[Ch4];
	motor[L2]= -1*vexRT[Ch4];
	motor[L2]= -1*vexRT[Ch4];

}


}
