#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftDrive,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

while(1 == 1)
{
motor[leftDrive] = (vexRT[Ch2] + vexRT[Ch1]); // (y + x)/2
motor[rightDrive] = (vexRT[Ch2] - vexRT[Ch1]); // (y - x)/2
}


}
