#pragma config(Motor,  port1,           R1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           R2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           L1,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           L2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           M1,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while (true)
{
	motor[R1]=vexRT[Ch2];
	motor[R2]=vexRT[Ch2];
	motor[L1]=vexRT[Ch3];
	motor[L2]=vexRT[Ch3];
}


}
