#pragma config(Sensor, dgtl9,  ArmEncoder,     sensorQuadEncoder)
#pragma config(Sensor, dgtl11, ArmTouch2,      sensorTouch)
#pragma config(Sensor, dgtl12, ArmTouch1,      sensorTouch)
#pragma config(Motor,  port1,           backRight,     tmotorVex393_HBridge, openLoop, driveRight)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           armRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armRight2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armLeft2,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          middleLeft,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR Team 8370   				 */
/*                                                                           */
/*        Autnonomous code: begins on line 71                                */
/*        Driver code: begins on line 95                                     */
/*                                                                           */
/*                                                                           */
/*                                                                           */
/*                                                                           */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	//raise arm 90 degrees (to knock stars)
	SensorValue[ArmEncoder] = 0;
	while(SensorValue[ArmEncoder] < 90) {
		motor[armLeft] = 127;
		motor[armLeft2] = 127;
		motor[armRight] = -127;
		motor[armRight2] = -127;
	}
	// Stop arm
	motor[armLeft] = 0;
	motor[armLeft2] = 0;
	motor[armRight] = 0;
	motor[armRight2] = 0;

	// drive forward 2 tiles
	motor[backRight]=127;
	motor[backLeft]=127;
	motor[frontRight]=127;
	motor[frontLeft]=127;
	wait1Msec(1200);

	// back up 1 tile
	motor[backRight]=-127;
	motor[backLeft]=-127;
	motor[frontRight]=-127;
	motor[frontLeft]=-127;
	wait1Msec(900);
	//Right square

	// DO NOT REMOVE BELOW WITHOUT ASKING ANISH.
  AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code inside the loop

  while (true)
  {

	  	float SpeedDivisor = 1;
	  	float backLimit = SensorValue[ArmTouch1] + SensorValue[ArmTouch2];
			float LeftDrive = vexRT[Ch3]/SpeedDivisor, RightDrive = vexRT[Ch2]/SpeedDivisor;
	  	motor[frontLeft] = LeftDrive;
	  	motor[backLeft] = LeftDrive;
	  	motor[frontRight] = RightDrive;
	  	motor[backRight] = RightDrive;

			/*
    	if(vexRT[Btn5U] == 1)	// if button 6U is pressed, arm goes down
			{ motor[middleLeft] = vexRT[Ch1];}
			else
			{motor[middleLeft] = 0;}
			*/

			/* combo moves*/

			// charge position
  		if(vexRT[Btn7U] == 1 && backLimit == 0)
    	{
				motor[armLeft] = 127;
				motor[armLeft2] = 127;
				motor[armRight] = -127;
				motor[armRight2] = -127;
				wait1Msec(900);
			}
			// defend position
			if(vexRT[Btn7D] == 1 && backLimit == 0)
			{
				motor[armLeft] = 127;
				motor[armLeft2] = 127;
				motor[armRight] = -127;
				motor[armRight2] = -127;
				wait1Msec(900);
			}
				// hold (45) position
		if(vexRT[Btn7L] == 1 && backLimit == 0)
			{
				motor[armLeft] = 127;
				motor[armLeft2] = 127;
				motor[armRight] = -127;
				motor[armRight2] = -127;
				wait1Msec(600);
			}
				// dump move
		if(vexRT[Btn7R] == 1 && backLimit == 0)
			{
				motor[armLeft] = 127;
				motor[armLeft2] = 127;
				motor[armRight] = -127;
				motor[armRight2] = -127;
				wait1Msec(1200);
			}
				// Recover move
		if(vexRT[Btn8U] == 1)	// if button 6U is pressed, arm goes down
			{
				motor[armLeft] = -127;
				motor[armLeft2] = -127;
				motor[armRight] = 127;
				motor[armRight2] = 127;
				wait1Msec(400);
			}

			/*

			TRIGGERS


			*/
			//slow arm

		if(vexRT[Btn5U] == 1 && backLimit == 0)	// if button 6U is pressed, arm goes down
			{
				motor[armLeft] = 115;
				motor[armLeft2] = 115;
				motor[armRight] = -115;
				motor[armRight2] = -115;
			}
		if(vexRT[Btn5D] == 1)	// if button 6U is pressed, arm goes down
			{
				motor[armLeft] = -115;
				motor[armLeft2] = -115;
				motor[armRight] = 115;
				motor[armRight2] = 115;
			}
			// fast arm
		if(vexRT[Btn6U] == 1 && backLimit == 0 )	// if button 6U is pressed, arm goes down
			{
				motor[armLeft] = 127;
				motor[armLeft2] = 127;
				motor[armRight] = -127;
				motor[armRight2] = -127;
			}
	 	 else if(vexRT[Btn6D] == 1) // if button 6D is pressed, arm goes down
			{
				motor[armLeft] = -127;
				motor[armLeft2] = -127;
				motor[armRight] = 127;
				motor[armRight2] = 127;
			}
		else // if button 6D is pressed, arm goes down
			{
				motor[armLeft] = 0;
				motor[armLeft2] = 0;
				motor[armRight] = 0;
				motor[armRight2] = 0;
			}
			/* Hold arm in position*/

	}
    // DO NOT REMOVE BELOW WITHOUT ASKING ANISH.
    UserControlCodePlaceholderForTesting();
  }
