#pragma config(Motor,  port1,           Belt,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           BackLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           BackRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           FrontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           mechFrontLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mechBackLeft,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           mechBackRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mechFrontRight, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// All movement functions half-speed
void forwardHalf(float time_sec) {
	motor[BackLeft] = 63;
	motor[BackRight] = 63;
	motor[FrontLeft] = 63;
	motor[FrontRight] = 63;

	wait(time_sec);
}
void backHalf(float time_sec) {
	motor[BackLeft] = -63;
	motor[BackRight] = -63;
	motor[FrontLeft] = -63;
	motor[FrontRight] = -63;

	wait(time_sec);
}

void leftHalf(float time_sec) {
	motor[BackLeft] = -63;
	motor[BackRight] = 63;
	motor[FrontLeft] = -63;
	motor[FrontRight] = 63;

	wait(time_sec);
}
void rightHalf(float time_sec) {
	motor[BackLeft] = 63;
	motor[BackRight] = -63;
	motor[FrontLeft] = 63;
	motor[FrontRight] = -63;

	wait(time_sec);
}

// Diagonal movement for quick maneuvering
void crabL(float time_sec) {
	motor[BackLeft] = 63;
	motor[BackRight] = -63;
	motor[FrontLeft] = -63;
	motor[FrontRight] = 63;

	wait(time_sec);
}
void crabR(float time_sec) {
	motor[BackLeft] = -63;
	motor[BackRight] = 63;
	motor[FrontLeft] = 63;
	motor[FrontRight] = -63;

	wait(time_sec);
}
void spinUp(float time_sec) {
	motor[mechFrontLeft] = 127;
	motor[mechBackLeft] = 127;
	motor[mechFrontRight] = 127;
	motor[mechBackRight] = 127;

	wait(time_sec);
}
void spinDn() {
	motor[mechFrontLeft] = 127;
	motor[mechBackLeft] = 127;
	motor[mechFrontRight] = 127;
	motor[mechBackRight] = 127;
}
void beltUp(float time_sec) {
	motor[Belt] = -127;
	wait(0.2);
	motor[Belt] = -80;
	wait(time_sec);
	motor[Belt] = 0;
}

void moveStop() {
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
}

task main()
{
	forwardHalf(5);
	moveStop();
	spinUp(3);
	beltUp(5);
	spinDn();

}
