#pragma config(Motor,  port1,           Belt,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           BackLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           BackRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           FrontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           mechFrontLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mechBackLeft,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           mechBackRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mechFrontRight, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// All movement functions half-speed
void forwardHalf(float time_sec) {
		motor[BackLeft] = 63;
		motor[BackRight] = 63;
		motor[FrontLeft] = 63;
		motor[FrontRight] = 63;

		wait(time_sec);
	}
void backHalf(float time_sec) {
		motor[BackLeft] = -63;
		motor[BackRight] = -63;
		motor[FrontLeft] = -63;
		motor[FrontRight] = -63;

		wait(time_sec);
	}

void leftHalf(float time_sec) {
		motor[BackLeft] = -63;
		motor[BackRight] = 63;
		motor[FrontLeft] = -63;
		motor[FrontRight] = 63;

		wait(time_sec);
	}
void rightHalf(float time_sec) {
		motor[BackLeft] = 63;
		motor[BackRight] = -63;
		motor[FrontLeft] = 63;
		motor[FrontRight] = -63;

		wait(time_sec);
	}

	// Diagonal movement for quick maneuvering
	void crabL(float time_sec) {
		motor[BackLeft] = 63;
		motor[BackRight] = -63;
		motor[FrontLeft] = -63;
		motor[FrontRight] = 63;

		wait(time_sec);
	}
	void crabR(float time_sec) {
		motor[BackLeft] = -63;
		motor[BackRight] = 63;
		motor[FrontLeft] = 63;
		motor[FrontRight] = -63;

		wait(time_sec);
	}
	void spinUp() {
		motor[mechFrontLeft] = 127;
		motor[mechBackLeft] = 127;
		motor[mechFrontRight] = 127;
		motor[mechBackRight] = 127;
	}
	void spinDn() {
		motor[mechFrontLeft] = 127;
		motor[mechBackLeft] = 127;
		motor[mechFrontRight] = 127;
		motor[mechBackRight] = 127;
	}
	void shootAll() {
		motor[Belt] = 127;
		wait(3);
		motor[Belt] = 0;
	}

task main()
{
	shootAll();
	forwardHalf(2.5);
	crabR(1);
	forwardHalf(2);
	spinUp();
	crabL(1);
	spinDn();

}
