#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           FrontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           BackRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           BackLeft,      tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           Belt1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Belt2,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// All movement functions half-speed
void forwardFull(float time_sec) {
	motor[BackLeft] = 127;
	motor[BackRight] = 75;
	motor[FrontLeft] = 127;
	motor[FrontRight] = 75;

	wait(time_sec);
}
void backFull(float time_sec) {
	motor[BackLeft] = -127;
	motor[BackRight] = -127;
	motor[FrontLeft] = -127;
	motor[FrontRight] = -127;

	wait(time_sec);
}
void leftFull(float time_sec) {
	motor[BackLeft] = -127;
	motor[BackRight] = 127;
	motor[FrontLeft] = -127;
	motor[FrontRight] = 127;

	wait(time_sec);
}
void rightFull(float time_sec) {
	motor[BackLeft] = 127;
	motor[BackRight] = -127;
	motor[FrontLeft] = 127;
	motor[FrontRight] = -127;

	wait(time_sec);
}

void beltUp(float time_sec) {
	motor[Belt1] = 127;
	motor[Belt2] = 127;

	wait(time_sec);
}
void beltDown(float time_sec) {
	motor[Belt1] = -127;
	motor[Belt2] = -127;

	wait(time_sec);
}

void moveStop() {
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
}

task main()
{
	forwardFull(8);
	moveStop();
	beltUp(10);
}
