#pragma config(Motor,  port1,           Belt,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           BackLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           BackRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           FrontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           mechFrontLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mechBackLeft,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           mechBackRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mechFrontRight, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

void forwardHalf(float time_sec) {
	motor[BackLeft] = 63;
	motor[BackRight] = 63;
	motor[FrontLeft] = 63;
	motor[FrontRight] = 63;

	wait(time_sec);
}
void backHalf(float time_sec) {
	motor[BackLeft] = -63;
	motor[BackRight] = -63;
	motor[FrontLeft] = -63;
	motor[FrontRight] = -63;

	wait(time_sec);
}
void leftHalf(float time_sec) {
	motor[BackLeft] = -63;
	motor[BackRight] = 63;
	motor[FrontLeft] = -63;
	motor[FrontRight] = 63;

	wait(time_sec);
}
void rightHalf(float time_sec) {
	motor[BackLeft] = 63;
	motor[BackRight] = -63;
	motor[FrontLeft] = 63;
	motor[FrontRight] = -63;

	wait(time_sec);
}

// Sideways movement
void crabL(float time_sec) {
	motor[BackLeft] = 63;
	motor[BackRight] = -63;
	motor[FrontLeft] = -63;
	motor[FrontRight] = 63;

	wait(time_sec);
}
void crabR(float time_sec) {
	motor[BackLeft] = -63;
	motor[BackRight] = 63;
	motor[FrontLeft] = 63;
	motor[FrontRight] = -63;

	wait(time_sec);
}

void spinUp(float time_sec) {
	motor[mechFrontLeft] = 127;
	motor[mechBackLeft] = 127;
	motor[mechFrontRight] = 127;
	motor[mechBackRight] = 127;

	wait(time_sec);
}
void spinDn() {
	motor[mechFrontLeft] = 127;
	motor[mechBackLeft] = 127;
	motor[mechFrontRight] = 127;
	motor[mechBackRight] = 127;
}
void beltUp(float time_sec) {
	motor[Belt] = -127;
	wait(0.2);
	motor[Belt] = -80;
	wait(time_sec);
	motor[Belt] = 0;
}

void moveStop() {
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	forwardHalf(5);
	moveStop();
	spinUp(3);
	beltUp(5);
	spinDn();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{

	while (true)
	{
	  /*
		* Controls the robot's movement in an arcade style using the left stick (LS).
		*/
		int LSy = vexRT[Ch3]; // Between -127 and 127
		int LSx = vexRT[Ch4]; // ^
		int RSy = vexRT[Ch2]; // ^
		int RB = vexRT[Btn6D]; // Either 0 or 1

		// Move at half speed
		motor[FrontLeft] = (LSy + LSx) / 2;
		motor[BackLeft] = (LSy + LSx) / 2;
		motor[FrontRight] = (LSy - LSx) / 2;
		motor[BackRight] = (LSy - LSx) / 2;

		if (RB == 1) {
			// Right Trigger : Spin shooter full speed (with belt control).
			motor[mechFrontLeft] = 127;
			motor[mechBackLeft] = 127;
			motor[mechFrontRight] = 127;
			motor[mechBackRight] = 127;
		} else {
			motor[mechFrontLeft] = 0;
			motor[mechBackLeft] = 0;
			motor[mechFrontRight] = 0;
			motor[mechBackRight] = 0;
		}

		// Right Stick controls ball belt.
		motor[Belt] = RSy;
	}
}
