#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port3,           FrontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           BackRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           BackLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           ShootRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           ShootLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Belt,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

void forwardFull(float time_sec) {
	motor[BackLeft] = 127;
	motor[BackRight] = 75;
	motor[FrontLeft] = 127;
	motor[FrontRight] = 75;

	wait(time_sec);
}
void backFull(float time_sec) {
	motor[BackLeft] = -127;
	motor[BackRight] = -127;
	motor[FrontLeft] = -127;
	motor[FrontRight] = -127;

	wait(time_sec);
}
void leftFull(float time_sec) {
	motor[BackLeft] = -127;
	motor[BackRight] = 127;
	motor[FrontLeft] = -127;
	motor[FrontRight] = 127;

	wait(time_sec);
}
void rightFull(float time_sec) {
	motor[BackLeft] = 127;
	motor[BackRight] = -127;
	motor[FrontLeft] = 127;
	motor[FrontRight] = -127;

	wait(time_sec);
}

void startShoot(int power) {
	motor[shootRight] = power;
	motor[shootLeft] = power;
}
void endShoot() {
	motor[shootRight] = 0;
	motor[shootLeft] = 0;
}

void beltUp(float time_sec) {
	motor[Belt] = 127;

	wait(time_sec);
}
void beltDown(float time_sec) {
	motor[Belt] = -127;

	wait(time_sec);
}
void beltStop() {
	motor[Belt] = 0;
	}

void moveStop() {
	motor[BackLeft] = 0;
	motor[BackRight] = 0;
	motor[FrontLeft] = 0;
	motor[FrontRight] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	startShoot(127);
	beltUp(1.5);
	beltStop();
	beltUp(1.5);
	beltStop();
	beltUp(1.5);
	beltStop();
	endShoot();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{

	while (true)
	{
	  /*
		* Controls the robot's movement in an arcade style using the left stick (LS).
		*/
		int LSy = vexRT[Ch3]; // Between -127 and 127
		int LSx = vexRT[Ch4]; // ^
		int RSy = vexRT[Ch2]; // ^
		int RF = vexRT[Btn6U]; // Either 0 or 1
		int RB = vexRT[Btn6D]; // ^
		int LF = vexRT[Btn5U]; // ^
		int LB = vexRT[Btn5D]; // ^

		// Move at half speed unless the left trigger is pressed
		if (LF || LB) {
			motor[FrontLeft] = LSy - LSx;
			motor[BackLeft] = LSy - LSx;
			motor[FrontRight] = LSy + LSx;
			motor[BackRight] = LSy + LSx;
		} else {
			motor[FrontLeft] = (LSy - LSx)/2;
			motor[BackLeft] = (LSy - LSx)/2;
			motor[FrontRight] = (LSy + LSx)/2;
			motor[BackRight] = (LSy + LSx)/2;
		}

		// Right Stick controls ball belt.
		motor[Belt] = RSy;

		if (RB) {
			startShoot(127);
		} else if (RF) {
			startShoot(63);
		} else {
			endShoot();
		}
	}
}
