#pragma config(Motor,  port1,           Belt,          tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           BackLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           BackRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           FrontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,           mechFrontLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mechBackLeft,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           mechBackRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mechFrontRight, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {

	while(true) {
		/*
		* Controls the robot's movement in an arcade style using the left stick (LS).
		*/
		int LSy = vexRT[Ch3]; // Between -127 and 127
		int LSx = vexRT[Ch4]; // ^
		int RSy = vexRT[Ch2]; // ^
		int RB = vexRT[Btn6D]; // Either 0 or 1

		// Move at half speed
		motor[FrontLeft] = (LSy + LSx) / 2;
		motor[BackLeft] = (LSy + LSx) / 2;
		motor[FrontRight] = (LSy - LSx) / 2;
		motor[BackRight] = (LSy - LSx) / 2;

		if (RB == 1) {
			// Right Trigger : Spin shooter full speed (with belt control).
			motor[mechFrontLeft] = 127;
			motor[mechBackLeft] = 127;
			motor[mechFrontRight] = 127;
			motor[mechBackRight] = 127;
		} else {
			motor[mechFrontLeft] = 0;
			motor[mechBackLeft] = 0;
			motor[mechFrontRight] = 0;
			motor[mechBackRight] = 0;
		}

		// Right Stick controls ball belt.
		motor[Belt] = RSy;
	}
}
