#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FrontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           BackLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BackRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mechFrontLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mechFrontRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           mechBackLeft,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           mechBackRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Belt,          tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {

	while(true) {
		/*
		* Controls the robot's movement in an arcade style using the left stick (LS).
		*/
		int LSy = vexRT[Ch3]; // Between -127 and 127
		int LSx = vexRT[Ch4]; // ^
		int RSy = vexRT[Ch2]; // ^
		int LF = vexRT[Btn5U]; // Either 0 or 1
		int RF = vexRT[Btn6U]; // ^

		if (LF == 1) {
			motor[FrontLeft] = LSy + LSx;
			motor[BackLeft] = LSy + LSx;
			motor[FrontRight] = LSy - LSx;
			motor[BackRight] = LSy - LSx;
		} else {
			motor[FrontLeft] = (LSy + LSx) / 2;
			motor[BackLeft] = (LSy + LSx) / 2;
			motor[FrontRight] = (LSy - LSx) / 2;
			motor[BackRight] = (LSy - LSx) / 2;
		}

		if (RF == 1) {
			motor[mechFrontLeft] = 127;
			motor[mechBackLeft] = 127;
			motor[mechFrontRight] = 127;
			motor[mechBackRight] = 127;
		}

		motor[Belt] = RSy; // The belt to carry balls toward shooter mech
	}
}
