#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backRight,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(1 == 1)
	{
	motor[frontLeft] = (vexRT[Ch2] + vexRT[Ch1])/2; // (y + x)/2
	motor[frontRight = (vexRT[Ch2] + vexRT[Ch1])/2; // (y + x)/2
	motor[backLeft] = (vexRT[Ch2] - vexRT[Ch1])/2; // (y - x)/2
	motor[backRight] = (vexRT[Ch2] - vexRT[Ch1])/2; // (y - x)/2
	}

}
