#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FrontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           BackLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BackRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mech_1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mech_2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mech_3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           mech_4,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Belt,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {

	while(true) {
		/*
		* Controls the robot's movement in an arcade style using the left stick (LS).
		*/
		int LSy = vexRT[Ch3]; // Between -127 and 127 before divided
		int LSx = vexRT[Ch4]; // ^
		int RSy = vexRT[Ch2]; // ^
		int LF = vexRT[Btn5U]; // Either 0 or 1

		if (LF == 1) {
			motor[FrontLeft] = LSy + LSx;
			motor[BackLeft] = LSy + LSx;
			motor[FrontRight] = LSy - LSx;
			motor[BackRight] = LSy - LSx;
		} else {
			motor[FrontLeft] = (LSy + LSx) / 2;
			motor[BackLeft] = (LSy + LSx) / 2;
			motor[FrontRight] = (LSy - LSx) / 2;
			motor[BackRight] = (LSy - LSx) / 2;
		}

		motor[Belt] = RSy; // The belt to carry balls toward shooter mech
	}
}
