#pragma config(Motor,  port1,           leftDrive,     tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           rightDrive,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightShootA,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightShootB,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftShootA,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftShootB,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           belt,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
 //
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	clearTimer(T1);
	// time less than 1 second
	while(time1[T1] < 1000)
	{
		// drive foward one second
		motor[rightDrive] = 63;
		motor[leftDrive] = 63;
	}
	while(time1[T1] < 1800)
	{
		// turn
		motor[rightDrive] = 63;
		motor[leftDrive] = -63;
	}
	while(time1[T1] < 5650)
	{
		// stop moving
		motor[rightDrive] = 0;
		motor[leftDrive] = 0;
		// start shooters and belt
		motor(rightShootB) = 78;
		motor(leftShootB) = 78;
		motor(rightShootA) = 78;
		motor(leftShootA) = 78;
	}
	while(time1[T1] < 6650)
	{
		motor[belt] = 127;
	}
	while(time1[T1] < 7650)
	{
		motor[belt] = 0;
	}
	while(time1[T1] < 8650)
	{
		motor[belt] = 127;
	}
	while(time1[T1] < 9650)
	{
		motor[belt] = 0;
	}
	while(time1[T1] < 15000)
	{
		motor[belt] = 127;
	}
	AutonomousCodePlaceholderForTesting();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop


	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.
		if (vexRT[Btn8R] == 1) {
			startTask(autonomous);
		}

		int LSy = vexRT[Ch3]; // Between -127 and 127
		int RSy = vexRT[Ch2]; // ^

		/*
		* DRIVE
		*/
		motor[leftDrive] = LSy; // Left Motor
		motor[rightDrive] = RSy; // Right Motor

		/*
		* Shoot
		*/

		// power 1
		while (vexRT[Btn7U] == 1)
		{
			motor(rightShootB) = 75;
			motor(leftShootB) = 75;
			motor(rightShootA) = 75;
			motor(leftShootA) = 75;
		}

		// power 2
		while (vexRT[Btn7L] == 1)
		{
			motor(rightShootB) = 80;
			motor(leftShootB) = 80;
			motor(rightShootA) = 80;
			motor(leftShootA) = 80;
		}

		// power 3
		while (vexRT[Btn7D] == 1)
		{
			motor(rightShootB) = 85;
			motor(leftShootB) = 85;
			motor(rightShootA) = 85;
			motor(leftShootA) = 85;
		}

		// power 4
		while (vexRT[Btn7R] == 1)
		{
			motor(rightShootB) = 90;
			motor(leftShootB) = 90;
			motor(rightShootA) = 90;
			motor(leftShootA) = 90;
 		}

 		// power 5
		while (vexRT[Btn8L] == 1)
		{
			motor(rightShootB) = 95;
			motor(leftShootB) = 95;
			motor(rightShootA) = 95;
			motor(leftShootA) = 95;
 		}

 		// power 6
		while (vexRT[Btn8D] == 1)
		{
			motor(rightShootB) = 100;
			motor(leftShootB) = 100;
			motor(rightShootA) = 100;
			motor(leftShootA) = 100;
		}

		 // power 7
		while (vexRT[Btn8R] == 1)
		{
			motor(rightShootB) = 105;
			motor(leftShootB) = 105;
			motor(rightShootA) = 105;
			motor(leftShootA) = 105;
		}
		
		 // stop
		while (vexRT[Btn5U] == 1)
		{
			motor(rightShootB) = 0;
			motor(leftShootB) = 0;
			motor(rightShootA) = 0;
			motor(leftShootA) = 0;
		}
		/*
		* Belt
		*/
		while (vexRT[Btn8U] == 1)
		{
			motor(belt) = 127;
		}
		while (vexRT[Btn6U] == 1)
		{
			motor(belt) = 0;
		}

		UserControlCodePlaceholderForTesting();
	}
}
