#pragma config(Motor,  port2,           rightOut,      tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           rightIn,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           leftOut,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           leftIn,        tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           rightFront,    tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           leftFront,     tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           rightRear,     tmotorVex393TurboSpeed_MC29, openLoop, driveRight)
#pragma config(Motor,  port9,           leftRear,      tmotorVex393TurboSpeed_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(215)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
 //
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	clearTimer(T1);
	// time less than 1 second
	while(time1[T1] < 1000)
	{
		// drive foward one second
		// motor[rightDrive] = 63;
		// motor[leftDrive] = 63;
	}
	while(time1[T1] < 1800)
	{
		// turn
		// motor[rightDrive] = 63;
		// motor[leftDrive] = -63;
	}

	AutonomousCodePlaceholderForTesting();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop


	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.


		int LSy = vexRT[Ch3]; // Between -127 and 127
		int RSy = vexRT[Ch2]; // ^
		motor[leftFront] = LSy; // Left Motor
		motor[leftRear] = LSy;
		motor[rightFront] = RSy;
		motor[rightRear] = RSy; // Right Motor


		if (vexRT[Btn8U] == 1)
		{
			motor(leftOut) = 127;
			motor(leftIn) = 127;
			//motor(rightOut) = 127;
			//motor(rightIn) = 127;
		}

			if (vexRT[Btn8D] == 1)
		{
		motor(leftOut) = -127;
		motor(leftIn) = -127;
		//	motor(rightOut) = -127;
		//	motor(rightIn) = -127;
		}

		if (vexRT[Btn8L] == 1)
		{
			motor(leftOut) = 0;
			motor(leftIn) = 0;
			motor(rightOut) = 0;
			motor(rightIn) = 0;
		}

		UserControlCodePlaceholderForTesting();
	}
}
// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
//#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

//void pre_auton()
//{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  //bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
//}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//task autonomous()
//{
  // ..........................................................................
  // Insert user code here.
  // ..........................................................................

  // Remove this function call once you have "real" code.
 // AutonomousCodePlaceholderForTesting();
//}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//task usercontrol()
//{
  // User control code here, inside the loop

 // while (true)
 // {
    // This is the main execution loop for the user control program.
    // Each time through the loop your program should update motor + servo
    // values based on feedback from the joysticks.

    // ........................................................................
    // Insert user code here. This is where you use the joystick values to
    // update your motors, etc.
    // ........................................................................

    // Remove this function call once you have "real" code.
   // UserControlCodePlaceholderForTesting();
  //}
//}
