#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           FrontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           BackLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           BackRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;
}

task autonomous()
{

}

task usercontrol()
{
  while (true)
  {
  	motor[FrontLeft] = vexRT[Ch3] + vexRT[Ch4];
  	motor[FrontRight] = vexRT[Ch3] - vexRT[Ch4];
  	motor[BackLeft] = vexRT[Ch3] + vexRT[Ch4];
  	motor[BackRight] = vexRT[Ch3] - vexRT[Ch4];
  }
}
#
