#pragma config(Sensor, dgtl9,  backe,          sensorQuadEncoder)
#pragma config(Sensor, dgtl11, righte,         sensorQuadEncoder)
#pragma config(Motor,  port2,           back,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           front,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           left,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           crighttop,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           clefttop,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           crightbot,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           cleftbot,      tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

/*
*	Stops all motors
*/
void stopm() {
		motor[front] = 0;
		motor[back] = 0;
		motor[left] = 0;
		motor[right] = 0;

		motor[crighttop] = 0;
		motor[crightbot] = 0;
		motor[clefttop] = 0;
		motor[cleftbot] = 0;
}

/*
* Moves the robot in direction (1 or -1) idistance number of inches.
*/
void forbac(float idistance, int speed, int direction){
	SensorValue[righte] = 0;
	while (abs(SensorValue[righte]) < 360 * (idistance/17)){
			motor[left] = (speed * direction) - 50; // Additions to equalize drift
			motor[right] = (speed * direction) + 50;
	}
	stopm();
}

void turn(int direction){
		motor[left] = -64 * direction;
		motor[right] = 64 * direction;
		motor[front] = -64 * direction;
		motor[back] = 64 * direction;

		wait1Msec(1100);
		stopm();
}

void cforbac(long timeMS, int speed, int direction) {
		motor[crighttop] = speed*(direction);
		motor[crightbot] = speed*(direction);
		motor[clefttop] = speed*(direction);
		motor[cleftbot] = speed*(direction);

		wait1Msec(timeMS);
		stopm();
	}

void pre_auton()
{

  bStopTasksBetweenModes = true;
}

task autonomous()
{
	forbac(12, 100, 1);
	forbac(2, 127, -1);
	forbac(2, 127, 1);
	forbac(2, 127, -1);
	forbac(44, 127, 1);
	forbac(34, 127, -1);

	cforbac(1800, 127, 1);
	forbac(30, 127, 1);
	turn(1);
	forbac(50, 127, 1);

}

task usercontrol()
{

	while(true){
		/*Driving*/

		float speedDivisor = 2-vexRT[Btn6U];
		float ForwDrive = vexRT[Ch3] / speedDivisor;
		float SideDrive = vexRT[Ch4] / speedDivisor;
		float turnSpeed = vexRT[Ch1] / speedDivisor; // Right stick determines turning speed
		motor[left] = ForwDrive - turnSpeed;
		motor[right] = ForwDrive + turnSpeed;
		motor[front] = -SideDrive - turnSpeed;
		motor[back] = -SideDrive + turnSpeed;
		/*Moving Arm*/

		float up = vexRT[Btn6D];
		float down = vexRT[Btn5D];

		motor[crighttop] = 127*(up-down);
		motor[crightbot] = 127*(up-down);
		motor[clefttop] = 127*(up-down);
		motor[cleftbot] = 127*(up-down);
	}
}
