#pragma config(Motor,  port2,           FrontRight,    tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           FrontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           BackRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           BackLeft,      tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port6,           Belt1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Belt2,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {

	while(true) {
		/*
		* Controls the robot's movement in an arcade style using the left stick (LS).
		*/
		int LSy = vexRT[Ch3]; // Between -127 and 127
		int LSx = vexRT[Ch4]; // ^
		int RSy = vexRT[Ch2]; // ^
		int RB = vexRT[Btn6D]; // Either 0 or 1

		// Move at full speed
		motor[FrontLeft] = LSy + LSx;
		motor[BackLeft] = LSy + LSx;
		motor[FrontRight] = LSy - LSx;
		motor[BackRight] = LSy - LSx;

		// Right Stick controls ball belt.
		motor[Belt1] = RSy;
		motor[Belt2] = RSy;
	}
}
