#pragma config(Motor,  port1,           bld,           tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           frd,           tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           brd,           tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           rst,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rsb,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           lst,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           lsb,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           belt,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          fld,           tmotorVex393_HBridge, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	AutonomousCodePlaceholderForTesting();
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop


	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		//your program should update motor + servo values based on feedback from the joysticks.
		//if (vexRT[Btn5D] == 1) {
		//	startTask(autonomous);
		//}

		int LSy = vexRT[Ch3]; // Between -127 and 127
		int RSy = vexRT[Ch2]; // ^

		/*
		* DRIVE
		*/
		motor[fld] = LSy; // Left Motor
		motor[bld] = LSy;
		motor[frd] = RSy;
		motor[brd] = RSy; // Right Motor

		/*
		* Shoot
		*/
		while (vexRT[Btn7U] == 1)
		{
			motor(lst) = 127;
			motor(lsb) = 127;
			motor(rst) = 127;
			motor(rsb) = 127;
		}

		while (vexRT[Btn5U] == 1)
		{
			motor(lst) = 0;
			motor(lsb) = 0;
			motor(rst) = 0;
			motor(rsb) = 0;
		}

		while (vexRT[Btn8U] == 1)
		{
			clearTimer(T1);
			// time less than 1 second

			while(time1[T1] < 750)
			{
				motor(bld) = -80;
				motor(fld) = -80;
				motor(brd) = -80;
				motor(frd) = -80;
			}
			while(time1[T1] < 755)
			{
				motor(brd) = 40;
				motor(frd) = 40;
			}
		}
		while (vexRT[Btn8R] == 1)
		{
			clearTimer(T1);
			// time less than 1 second

			while(time1[T1] < 6000)
			{
				motor(bld) = 127;
				motor(fld) = 127;
				motor(brd) = 127;
				motor(frd) = 127;
			}
			while(time1[T1] < 6750)
			{
				motor(bld) = -80;
				motor(fld) = -80;
				motor(brd) = -80;
				motor(frd) = -80;
			}
			while(time1[T1] < 6755)
			{
				motor(brd) = 40;
				motor(frd) = 40;
			}
		}
		UserControlCodePlaceholderForTesting();
	}
}
